vim.keymap.set("n", ".", ":")
vim.keymap.set("n", ":", ":")
vim.keymap.set({"n", "v"}, "Ê", ".")
vim.keymap.set({"n", "v"}, "w", "$")
vim.keymap.set({"n", "v"}, "é", "w")
vim.keymap.set({"n", "v"}, "ç", "0")
